MONGODB_USERNAME = "username1234"
MONGODB_PASSWORD = "temporary_strong_pwd"
MONGODB_DB_NAME = "my-database"
MONGODB_COLLECTION_SENSOR_DATA = "sensor-collection"
MONGODB_CONNECTION_URI = f"mongodb+srv://{MONGODB_USERNAME}:{MONGODB_PASSWORD}@my-cluster.3p17a.mongodb.net/{MONGODB_DB_NAME}?retryWrites=true&w=majority"
FILEPATH_SENSOR_RECORDS = "../frontend/sensor-app/src/data/sensorRecordsSnapshot.json"
